// Wimbledon 2026 main singles draws.
// Source: official draw made 2026-06-26 (cross-checked against the published
// bracket). 128 players each, in draw order (slot 0 = top of the draw).
// `country` is an ISO 3166-1 alpha-2 code used to show a flag next to the name.

export const DRAWS = {
  men: [
    { name: 'J. Sinner', seed: 1, country: 'it' },
    { name: 'M. Kecmanovic', seed: null, country: 'rs' },
    { name: 'N. Borges', seed: null, country: 'pt' },
    { name: 'T. Boyer', seed: null, country: 'us' },
    { name: 'A. Vukic', seed: null, country: 'au' },
    { name: 'J. Brooksby', seed: null, country: 'us' },
    { name: 'E. Nava', seed: null, country: 'us' },
    { name: 'I. Buse', seed: 31, country: 'pe' },
    { name: 'R. Jodar', seed: 23, country: 'es' },
    { name: 'F. Gill', seed: null, country: 'gb' },
    { name: 'D. Shapovalov', seed: null, country: 'ca' },
    { name: 'P. Carreno Busta', seed: null, country: 'es' },
    { name: 'S. Mochizuki', seed: null, country: 'jp' },
    { name: 'M. Basing', seed: null, country: 'gb' },
    { name: 'E. Quinn', seed: null, country: 'us' },
    { name: 'L. Darderi', seed: 14, country: 'it' },
    { name: 'C. Ruud', seed: 11, country: 'no' },
    { name: 'H. Hurkacz', seed: null, country: 'pl' },
    { name: 'H. Medjedovic', seed: null, country: 'rs' },
    { name: 'S. Ofner', seed: null, country: 'at' },
    { name: 'S. Kwon', seed: null, country: 'kr' },
    { name: 'M. Landaluce', seed: null, country: 'es' },
    { name: 'A. Muller', seed: null, country: 'fr' },
    { name: 'T. Paul', seed: 21, country: 'us' },
    { name: 'B. Nakashima', seed: 28, country: 'us' },
    { name: 'J. Pinnington Jones', seed: null, country: 'gb' },
    { name: 'JL. Struff', seed: null, country: 'de' },
    { name: 'S. Baez', seed: null, country: 'ar' },
    { name: 'C. Ugo Carabelli', seed: null, country: 'ar' },
    { name: 'D. Merida', seed: null, country: 'es' },
    { name: 'M. Cilic', seed: null, country: 'hr' },
    { name: 'D. Medvedev', seed: 8, country: 'ru' },
    { name: 'F. Auger-Aliassime', seed: 3, country: 'ca' },
    { name: 'A. Shevchenko', seed: null, country: 'kz' },
    { name: 'A. Walton', seed: null, country: 'au' },
    { name: 'D. Prizmic', seed: null, country: 'hr' },
    { name: 'D. Vallejo', seed: null, country: 'py' },
    { name: 'N. Mejia', seed: null, country: 'co' },
    { name: 'M. Zheng', seed: null, country: 'us' },
    { name: 'C. Norrie', seed: 26, country: 'gb' },
    { name: 'A. Davidovich Fokina', seed: 22, country: 'es' },
    { name: 'JM. Cerundolo', seed: null, country: 'ar' },
    { name: 'TA. Tirante', seed: null, country: 'ar' },
    { name: 'F. Marozsan', seed: null, country: 'hu' },
    { name: 'L. Van Assche', seed: null, country: 'fr' },
    { name: 'M. Fucsovics', seed: null, country: 'hu' },
    { name: 'D. Svrcina', seed: null, country: 'cz' },
    { name: 'L. Tien', seed: 16, country: 'us' },
    { name: 'A. Rublev', seed: 12, country: 'ru' },
    { name: 'R. Safiullin', seed: null, country: 'ru' },
    { name: 'A. Kovacevic', seed: null, country: 'us' },
    { name: 'B. van de Zandschulp', seed: null, country: 'nl' },
    { name: 'J. de Jong', seed: null, country: 'nl' },
    { name: 'R. Hijikata', seed: null, country: 'au' },
    { name: 'R. Bautista Agut', seed: null, country: 'es' },
    { name: 'J. Fonseca', seed: 24, country: 'br' },
    { name: 'A. Rinderknech', seed: 25, country: 'fr' },
    { name: 'O. Tarvet', seed: null, country: 'gb' },
    { name: 'M. Trungelliti', seed: null, country: 'ar' },
    { name: 'M. Damm', seed: null, country: 'us' },
    { name: 'H. Gaston', seed: null, country: 'fr' },
    { name: 'S. Tsitsipas', seed: null, country: 'gr' },
    { name: 'Y. Wu', seed: null, country: 'cn' },
    { name: 'N. Djokovic', seed: 7, country: 'rs' },
    { name: 'A. de Minaur', seed: 5, country: 'au' },
    { name: 'R. Burruchaga', seed: null, country: 'ar' },
    { name: 'A. Mannarino', seed: null, country: 'fr' },
    { name: 'T. Droguet', seed: null, country: 'fr' },
    { name: 'M. Bellucci', seed: null, country: 'it' },
    { name: 'Z. Svajda', seed: null, country: 'us' },
    { name: 'K. Majchrzak', seed: null, country: 'pl' },
    { name: 'A. Tabilo', seed: 30, country: 'cl' },
    { name: 'K. Khachanov', seed: 19, country: 'ru' },
    { name: 'B. Harris', seed: null, country: 'gb' },
    { name: 'Y. Hanfmann', seed: null, country: 'de' },
    { name: 'G. Mpetshi Perricard', seed: null, country: 'fr' },
    { name: 'T. Griekspoor', seed: null, country: 'nl' },
    { name: 'J. Duckworth', seed: null, country: 'au' },
    { name: 'M. Navone', seed: null, country: 'ar' },
    { name: 'F. Cobolli', seed: 9, country: 'it' },
    { name: 'J. Mensik', seed: 15, country: 'cz' },
    { name: 'T. Samuel', seed: null, country: 'au' },
    { name: 'D. Sweeny', seed: null, country: 'au' },
    { name: 'G. Dimitrov', seed: null, country: 'bg' },
    { name: 'S. Wawrinka', seed: null, country: 'ch' },
    { name: 'M. Berrettini', seed: null, country: 'it' },
    { name: 'R. Collignon', seed: null, country: 'be' },
    { name: 'A. Fils', seed: 20, country: 'fr' },
    { name: 'U. Humbert', seed: 27, country: 'fr' },
    { name: 'Z. Bergs', seed: null, country: 'be' },
    { name: 'S. Shimabukuro', seed: null, country: 'jp' },
    { name: 'J. Faria', seed: null, country: 'pt' },
    { name: 'D. Dzumhur', seed: null, country: 'ba' },
    { name: 'A. Fery', seed: null, country: 'gb' },
    { name: 'O. Virtanen', seed: null, country: 'fi' },
    { name: 'B. Shelton', seed: 4, country: 'us' },
    { name: 'T. Fritz', seed: 6, country: 'us' },
    { name: 'J. Draper', seed: null, country: 'gb' },
    { name: 'P. Kypson', seed: null, country: 'us' },
    { name: 'M. McDonald', seed: null, country: 'us' },
    { name: 'B. Bonzi', seed: null, country: 'fr' },
    { name: 'G. Diallo', seed: null, country: 'ca' },
    { name: 'L. Sonego', seed: null, country: 'it' },
    { name: 'TM. Etcheverry', seed: 29, country: 'ar' },
    { name: 'F. Tiafoe', seed: 17, country: 'us' },
    { name: 'T. Atmane', seed: null, country: 'fr' },
    { name: 'V. Kopriva', seed: null, country: 'cz' },
    { name: 'J. Choinski', seed: null, country: 'gb' },
    { name: 'K. Jacquet', seed: null, country: 'fr' },
    { name: 'V. Gaubas', seed: null, country: 'lt' },
    { name: 'T. Kokkinakis', seed: null, country: 'au' },
    { name: 'A. Bublik', seed: 10, country: 'kz' },
    { name: 'J. Lehecka', seed: 13, country: 'cz' },
    { name: 'A. Popyrin', seed: null, country: 'au' },
    { name: 'A. Molcan', seed: null, country: 'sk' },
    { name: 'D. Altmaier', seed: null, country: 'de' },
    { name: 'A. Michelsen', seed: null, country: 'us' },
    { name: 'J. Fearnley', seed: null, country: 'gb' },
    { name: 'J. Munar', seed: null, country: 'es' },
    { name: 'F. Cerundolo', seed: 18, country: 'ar' },
    { name: 'M. Arnaldi', seed: 32, country: 'it' },
    { name: 'Q. Halys', seed: null, country: 'fr' },
    { name: 'C. Moutet', seed: null, country: 'fr' },
    { name: 'M. Giron', seed: null, country: 'us' },
    { name: 'V. Royer', seed: null, country: 'fr' },
    { name: 'H. Wendelken', seed: null, country: 'gb' },
    { name: 'A. Blockx', seed: null, country: 'be' },
    { name: 'A. Zverev', seed: 2, country: 'de' },
  ],
  women: [
    { name: 'A. Sabalenka', seed: 1, country: 'by' },
    { name: 'T. Kostovic', seed: null, country: 'rs' },
    { name: 'O. Oliynykova', seed: null, country: 'ua' },
    { name: 'M. Kessler', seed: null, country: 'us' },
    { name: 'J. Ostapenko', seed: null, country: 'lv' },
    { name: 'H. Dart', seed: null, country: 'gb' },
    { name: 'A. Ruzic', seed: null, country: 'hr' },
    { name: 'E. Raducanu', seed: 30, country: 'gb' },
    { name: 'L. Fernandez', seed: 22, country: 'ca' },
    { name: 'J. Tjen', seed: null, country: 'id' },
    { name: 'M. Xu', seed: null, country: 'gb' },
    { name: 'D. Kasatkina', seed: null, country: 'au' },
    { name: 'A. Gasanova', seed: null, country: 'ru' },
    { name: 'E. Arango', seed: null, country: 'co' },
    { name: 'E. Jacquemot', seed: null, country: 'fr' },
    { name: 'N. Osaka', seed: 14, country: 'jp' },
    { name: 'K. Muchova', seed: 10, country: 'cz' },
    { name: 'A. Zakharova', seed: null, country: 'by' },
    { name: 'B. Andreescu', seed: null, country: 'ca' },
    { name: 'S. Zhang', seed: null, country: 'cn' },
    { name: 'A. Parks', seed: null, country: 'us' },
    { name: 'A. Dudeney', seed: null, country: 'gb' },
    { name: 'M. Sawangkaew', seed: null, country: 'th' },
    { name: 'M. Chwalinska', seed: 20, country: 'pl' },
    { name: 'K. Siniakova', seed: 32, country: 'cz' },
    { name: 'Q. Zheng', seed: null, country: 'cn' },
    { name: 'P. Stearns', seed: null, country: 'us' },
    { name: 'N. Bartunkova', seed: null, country: 'cz' },
    { name: 'B. Krejcikova', seed: null, country: 'cz' },
    { name: 'H. Klugman', seed: null, country: 'gb' },
    { name: 'M. Linette', seed: null, country: 'pl' },
    { name: 'M. Andreeva', seed: 5, country: 'ru' },
    { name: 'J. Pegula', seed: 4, country: 'us' },
    { name: 'D. Vidmanova', seed: null, country: 'cz' },
    { name: 'S. Sorribes Tormo', seed: null, country: 'es' },
    { name: 'V. Jimenez Kasintseva', seed: null, country: 'ad' },
    { name: 'D. Yastremska', seed: null, country: 'ua' },
    { name: 'A. Ito', seed: null, country: 'jp' },
    { name: 'J. Bouzas Maneiro', seed: null, country: 'es' },
    { name: 'A. Potapova', seed: 27, country: 'at' },
    { name: 'E. Alexandrova', seed: 18, country: 'ru' },
    { name: 'P. Udvardy', seed: null, country: 'hu' },
    { name: 'L. Tararudee', seed: null, country: 'th' },
    { name: 'L. Tagger', seed: null, country: 'at' },
    { name: 'Y. Putintseva', seed: null, country: 'kz' },
    { name: 'T. Maria', seed: null, country: 'de' },
    { name: 'J. Cristian', seed: null, country: 'ro' },
    { name: 'I. Jovic', seed: 16, country: 'us' },
    { name: 'B. Bencic', seed: 11, country: 'ch' },
    { name: 'M. Stojsavljevic', seed: null, country: 'gb' },
    { name: 'X. Wang', seed: null, country: 'cn' },
    { name: 'E. Cocciaretto', seed: null, country: 'it' },
    { name: 'F. Jones', seed: null, country: 'gb' },
    { name: 'D. Parry', seed: null, country: 'fr' },
    { name: 'M. Frech', seed: null, country: 'pl' },
    { name: 'A. Kalinskaya', seed: 19, country: 'ru' },
    { name: 'A. Li', seed: 28, country: 'us' },
    { name: 'Z. Sonmez', seed: null, country: 'tr' },
    { name: 'C. Liu', seed: null, country: 'us' },
    { name: 'H. Vandewinkel', seed: null, country: 'be' },
    { name: 'S. Sierra', seed: null, country: 'ar' },
    { name: 'A. Bondar', seed: null, country: 'hu' },
    { name: 'T. Korpatsch', seed: null, country: 'de' },
    { name: 'C. Gauff', seed: 7, country: 'us' },
    { name: 'E. Svitolina', seed: 8, country: 'ua' },
    { name: 'D. Snigur', seed: null, country: 'ua' },
    { name: 'V. Erjavec', seed: null, country: 'si' },
    { name: 'L. Jeanjean', seed: null, country: 'fr' },
    { name: 'A. Tomljanovic', seed: null, country: 'au' },
    { name: 'M. Bolkvadze', seed: null, country: 'ge' },
    { name: 'A. Krueger', seed: null, country: 'us' },
    { name: 'D. Vekic', seed: 31, country: 'hr' },
    { name: 'E. Navarro', seed: 23, country: 'us' },
    { name: 'P. Badosa', seed: null, country: 'es' },
    { name: 'O. Selekhmeteva', seed: null, country: 'es' },
    { name: 'S. Kraus', seed: null, country: 'at' },
    { name: 'Y. Starodubtseva', seed: null, country: 'ua' },
    { name: 'A. Blinkova', seed: null, country: 'ru' },
    { name: 'N. Podoroska', seed: null, country: 'ar' },
    { name: 'M. Kostyuk', seed: 12, country: 'ua' },
    { name: 'J. Paolini', seed: 13, country: 'it' },
    { name: 'R. Montgomery', seed: null, country: 'us' },
    { name: 'I. Shymanovich', seed: null, country: 'by' },
    { name: 'V. Golubic', seed: null, country: 'ch' },
    { name: 'A. Kalinina', seed: null, country: 'ua' },
    { name: 'K. Rakhimova', seed: null, country: 'uz' },
    { name: 'M. Sakkari', seed: null, country: 'gr' },
    { name: 'C. Tauson', seed: 24, country: 'dk' },
    { name: 'A. Eala', seed: 29, country: 'ph' },
    { name: 'R. Zarazua', seed: null, country: 'mx' },
    { name: 'S. Williams', seed: null, country: 'us' },
    { name: 'M. Joint', seed: null, country: 'au' },
    { name: 'T. Valentova', seed: null, country: 'cz' },
    { name: 'K. Pliskova', seed: null, country: 'cz' },
    { name: 'T. Townsend', seed: null, country: 'us' },
    { name: 'I. Swiatek', seed: 3, country: 'pl' },
    { name: 'A. Anisimova', seed: 6, country: 'us' },
    { name: 'L. Gjorcheska', seed: null, country: 'mk' },
    { name: 'P. Marcinko', seed: null, country: 'hr' },
    { name: 'S. Kenin', seed: null, country: 'us' },
    { name: 'I.-C. Begu', seed: null, country: 'ro' },
    { name: 'K. Swan', seed: null, country: 'gb' },
    { name: 'K. Day', seed: null, country: 'us' },
    { name: 'M. Keys', seed: 26, country: 'us' },
    { name: 'S. Cirstea', seed: 17, country: 'ro' },
    { name: 'S. Bejlek', seed: null, country: 'cz' },
    { name: 'K. Birrell', seed: null, country: 'au' },
    { name: 'A. Korneeva', seed: null, country: 'ru' },
    { name: 'C. Osorio', seed: null, country: 'co' },
    { name: 'S. Waltert', seed: null, country: 'ch' },
    { name: 'E. Seidel', seed: null, country: 'de' },
    { name: 'L. Noskova', seed: 9, country: 'cz' },
    { name: 'D. Shnaider', seed: 15, country: 'ru' },
    { name: 'E. Lys', seed: null, country: 'de' },
    { name: 'P. Kudermetova', seed: null, country: 'uz' },
    { name: 'L. Samsonova', seed: null, country: 'ru' },
    { name: 'K. Boulter', seed: null, country: 'gb' },
    { name: 'T. C. Grant', seed: null, country: 'it' },
    { name: 'T. Gibson', seed: null, country: 'au' },
    { name: 'M. Bouzkova', seed: 21, country: 'cz' },
    { name: 'E. Mertens', seed: 25, country: 'be' },
    { name: 'L. Siegemund', seed: null, country: 'de' },
    { name: 'B. Haddad Maia', seed: null, country: 'br' },
    { name: 'M. Timofeeva', seed: null, country: 'uz' },
    { name: 'E. G. Ruse', seed: null, country: 'ro' },
    { name: 'C. McNally', seed: null, country: 'us' },
    { name: 'L. Boisson', seed: null, country: 'fr' },
    { name: 'E. Rybakina', seed: 2, country: 'kz' },
  ],
};
